CREATE DATABASE loja;

USE Loja;

-- LEMBRE-SE DE QUE ESTÁ USANDO O AUTO_INCREMENT E DE QUE QUASE TODAS AS COLUNAS SÃO NOT NULL --

-- TABELA SUBCATEGORIA CRIADA --
CREATE TABLE IF NOT EXISTS Subcategoria(

Cod_Subcategoria SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Nome_Subcategoria VARCHAR(60) NOT NULL,
Data_Subcategoria DATE NOT NULL

-- ALTER TABLE Subcategoria RENAME COLUMN Data_Subcategoria TO 'Nome_Novo' --
-- ALTER TABLE Subcategoria CHANGE COLUMN Data_Subcategoria 'Nome_Novo' VARCHAR(60)--
);

-- DATA NÃO É UMA PALAVRA RESERVADA, PORÉM DEVE SER EVITADA PARA NÃO CAUSAR CONFUSÃO  --
-- LEMBRE DE CORRIGIR O NOME 'DATA_SUBCATEGORIA' DEPOIS E EXPLICAR ISSO PARA A NAYARA -- 

-- TABELA CATEGORIA CRIADA --
CREATE TABLE IF NOT EXISTS Categoria(

Cod_Categoria SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Cod_Subcategoria SMALLINT NOT NULL,
FOREIGN KEY (Cod_Subcategoria) REFERENCES Subcategoria(Cod_Subcategoria),
Nome_Categoria VARCHAR(60) NOT NULL
);

-- TABELA PRODUTO CRIADA --
CREATE TABLE IF NOT EXISTS Produto(

Cod_Produto SMALLINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Cod_Categoria SMALLINT NOT NULL,
Nome_Produto VARCHAR(80) NOT NULL,
Descricao_Produto TEXT,
Preco_Produto FLOAT NOT NULL,
Peso_Produto FLOAT NOT NULL,
FOREIGN KEY(Cod_Categoria) REFERENCES Categoria(Cod_Categoria)
);

SELECT * FROM Subcategoria;
SELECT * FROM Categoria;
SELECT * FROM Produto;
